export const categories = [
  {
    id: "maintenance",
    name: "Maintenance",
    note: "Repairs, quotes, and contractor follow-up",
    icon: "M",
    color: "#0f766e",
  },
  {
    id: "break-lease",
    name: "Break Lease",
    note: "Break lease process, advertising, and inspections",
    icon: "B",
    color: "#b44b5f",
  },
  {
    id: "transfer-lease",
    name: "Transfer Lease",
    note: "Lease transfer documents, bond change, and incoming tenant confirmation",
    icon: "T",
    color: "#7c5c2e",
  },
  {
    id: "lease-renewal",
    name: "Lease Renewal",
    note: "Renewal offer, rent increase notice, and tenant response tracking",
    icon: "R",
    color: "#2d7a5f",
  },
  {
    id: "daily-task",
    name: "Daily Task",
    note: "Daily work record not linked to a property",
    icon: "D",
    color: "#2f6f9f",
  },
  {
    id: "move-in",
    name: "Move In",
    note: "New tenant move-in, keys, and condition report",
    icon: "I",
    color: "#6d5b98",
  },
  {
    id: "outgoing",
    name: "Outgoing",
    note: "Final inspection, bond claim, and tenant decision",
    icon: "O",
    color: "#9a5a2f",
  },
  {
    id: "letting-only",
    name: "Letting Only",
    note: "Letting-only acceptance, rent deposit, and owner bond payment",
    icon: "L",
    color: "#2f7d59",
  },
];
